In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('house_sale.csv')

In [5]:
df.head()

,id_x,rel_url,estate_rel_url_x,datetime_scrape_x,price,currency_x,location,attributes,city_when,city,...,Mərtəbə,Otaq sayı,Sahə,Torpaq sahəsi,Təmir,Çıxarış,İpoteka,estate_details_id_y,estate_rel_url,extra_info
0,5df36281-6dc6-4d5d-89a7-5fcfa86f7608,/alqi-satqi?page=174,/items/4521724,2024-10-05 22:07:37.60613+00,499999.0,AZN,Səbail r.,"4 otaqlı, 145 m², 7/9 mərtəbə","Bakı, dünən 23:52",bakı,...,7 / 9,4.0,145 m²,NaN,var,var,NaN,92e82ea2-e1f3-4c2d-a284-151efd99281e,/items/4521724,Şəhidlər xiyabanı * Dağüstü parkı * Səbail r.
1,883e20f0-8872-49a5-8b4b-63b8301b5f8f,/alqi-satqi?page=250,/items/4669294,2024-10-05 22:07:37.60613+00,77000.0,AZN,Biləcəri q.,"4 otaqlı, 90 m²","Bakı, dünən 23:56",bakı,...,NaN,4.0,90 m²,1.3 sot,var,yoxdur,NaN,505eaf81-6bc8-4094-9b00-aa82066548ee,/items/4669294,Binəqədi r.* Biləcəri q.
2,55c36fb1-a3af-476e-ba17-a81f6795be8d,/alqi-satqi?page=250,/items/4669293,2024-10-05 22:07:37.60613+00,92000.0,AZN,İnşaatçılar m.,"3 otaqlı, 60 m²","Bakı, dünən 23:55",bakı,...,NaN,3.0,60 m²,0.1 sot,var,var,NaN,fa63b201-999d-43b5-a61a-778d9d79a6c6,/items/4669293,İnşaatçılar m.* Yasamal r.
3,acf1aa8d-a46a-40f5-b6f2-f7a449569337,/alqi-satqi?page=250,/items/4647811,2024-10-05 22:07:37.60613+00,95000.0,AZN,Qaraçuxur q.,130 m²,"Bakı, dünən 23:55",bakı,...,NaN,NaN,130 m²,NaN,var,var,var,5db56980-05cc-4925-b55b-f58fb3f4d2b6,/items/4647811,Suraxanı r.* Qaraçuxur q.
4,22d840df-9283-4112-bc71-7432511fc776,/alqi-satqi?page=250,/items/4638863,2024-10-05 22:07:37.60613+00,220000.0,AZN,Əhmədli m.,"3 otaqlı, 100 m², 15/16 mərtəbə","Bakı, dünən 23:52",bakı,...,15 / 16,3.0,100 m²,NaN,var,var,NaN,d71cf9a9-86dd-4162-b540-6252a8659a09,/items/4638863,Əhmədli m.* Xalqlar Dostluğu m.* Xətai r.* Əhm...

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100775 entries, 0 to 100774
Data columns (total 51 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id_x                 100775 non-null  str
 1   rel_url              100775 non-null  str
 2   estate_rel_url_x     100775 non-null  str
 3   datetime_scrape_x    100775 non-null  str
 4   price                100775 non-null  float64
 5   currency_x           100775 non-null  str
 6   location             100775 non-null  str
 7   attributes           100775 non-null  str
 8   city_when            100775 non-null  str
 9   city                 100775 non-null  str
 10  day_x                100775 non-null  str
 11  hour_x               100775 non-null  str
 12  repair               81612 non-null   str
 13  vip                  8596 non-null    str
 14  featured             3149 non-null    str
 15  products_label       72630 non-null   str
 16  bill_of_sale         79565 non-null   str
 17  mortgage             32939 non-null   str
 18  img_url              100775 non-null  str
 19  id_y                 100775 non-null  str
 20  estate_id            100775 non-null  str
 21  estate_rel_url_y     100775 non-null  str
 22  datetime_scrape_y    100775 non-null  str
 23  description          100510 non-null  str
 24  unit_price           75996 non-null   str
 25  total_price          100775 non-null  float64
 26  currency_y           100775 non-null  str
 27  owner_name           100118 non-null  str
 28  owner_title          100118 non-null  str
 29  shop_name            72018 non-null   str
 30  shop_title           72018 non-null   str
 31  address              100775 non-null  str
 32  lat                  100775 non-null  float64
 33  lng                  100775 non-null  float64
 34  updated              100775 non-null  str
 35  views                100775 non-null  int64
 36  day_y                100775 non-null  str
 37  hour_y               15631 non-null   str
 38  estate_details_id_x  100775 non-null  str
 39  Binanın növü         154 non-null     str
 40  Kateqoriya           100775 non-null  str
 41  Mərtəbə              75996 non-null   str
 42  Otaq sayı            91363 non-null   float64
 43  Sahə                 100775 non-null  str
 44  Torpaq sahəsi        15571 non-null   str
 45  Təmir                94774 non-null   str
 46  Çıxarış              100775 non-null  str
 47  İpoteka              32939 non-null   str
 48  estate_details_id_y  100775 non-null  str
 49  estate_rel_url       100775 non-null  str
 50  extra_info           100775 non-null  str
dtypes: float64(5), int64(1), str(45)
memory usage: 39.2 MB

In [7]:
pd.set_option('display.max_columns', None)

In [8]:
df.head()

,id_x,rel_url,estate_rel_url_x,datetime_scrape_x,price,currency_x,location,attributes,city_when,city,day_x,hour_x,repair,vip,featured,products_label,bill_of_sale,mortgage,img_url,id_y,estate_id,estate_rel_url_y,datetime_scrape_y,description,unit_price,total_price,currency_y,owner_name,owner_title,shop_name,shop_title,address,lat,lng,updated,views,day_y,hour_y,estate_details_id_x,Binanın növü,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Torpaq sahəsi,Təmir,Çıxarış,İpoteka,estate_details_id_y,estate_rel_url,extra_info
0,5df36281-6dc6-4d5d-89a7-5fcfa86f7608,/alqi-satqi?page=174,/items/4521724,2024-10-05 22:07:37.60613+00,499999.0,AZN,Səbail r.,"4 otaqlı, 145 m², 7/9 mərtəbə","Bakı, dünən 23:52",bakı,05.10.2024,23:52,Təmirli,vipped,featured,NaN,Çıxarış var,NaN,https://bina.azstatic.com/uploads/f460x345/202...,92e82ea2-e1f3-4c2d-a284-151efd99281e,5df36281-6dc6-4d5d-89a7-5fcfa86f7608,/items/4521724,2024-10-05 22:14:10.089116+00,"Səbail Rayonu, İzzət Nəbiyev küçəsi, Fəxri Xiy...",3 450 AZN/m²,499999.0,AZN,Kamran,mülkiyyətçi,NaN,NaN,İzzət Nəbiyev küç.,40.358817,49.824092,yeniləndi: dünən 23:52,1155,05.10.2024,23:52,92e82ea2-e1f3-4c2d-a284-151efd99281e,NaN,Köhnə tikili,7 / 9,4.0,145 m²,NaN,var,var,NaN,92e82ea2-e1f3-4c2d-a284-151efd99281e,/items/4521724,Şəhidlər xiyabanı * Dağüstü parkı * Səbail r.
1,883e20f0-8872-49a5-8b4b-63b8301b5f8f,/alqi-satqi?page=250,/items/4669294,2024-10-05 22:07:37.60613+00,77000.0,AZN,Biləcəri q.,"4 otaqlı, 90 m²","Bakı, dünən 23:56",bakı,05.10.2024,23:56,Təmirli,NaN,NaN,NaN,NaN,NaN,https://bina.azstatic.com/uploads/f460x345/202...,505eaf81-6bc8-4094-9b00-aa82066548ee,883e20f0-8872-49a5-8b4b-63b8301b5f8f,/items/4669294,2024-10-05 22:14:10.089116+00,"Biləcəridə Abidəyə yaxin 91,92,202 saylı marşr...",NaN,77000.0,AZN,Dasinmaz Emlak,vasitəçi (agent),NaN,NaN,Biləcəri qəs.,40.420897,49.807035,yeniləndi: 04 oktyabr 2024,218,04.10.2024,NaN,505eaf81-6bc8-4094-9b00-aa82066548ee,NaN,Həyət evi/Bağ evi,NaN,4.0,90 m²,1.3 sot,var,yoxdur,NaN,505eaf81-6bc8-4094-9b00-aa82066548ee,/items/4669294,Binəqədi r.* Biləcəri q.
2,55c36fb1-a3af-476e-ba17-a81f6795be8d,/alqi-satqi?page=250,/items/4669293,2024-10-05 22:07:37.60613+00,92000.0,AZN,İnşaatçılar m.,"3 otaqlı, 60 m²","Bakı, dünən 23:55",bakı,05.10.2024,23:55,Təmirli,NaN,NaN,NaN,Çıxarış var,NaN,https://bina.azstatic.com/uploads/f460x345/202...,fa63b201-999d-43b5-a61a-778d9d79a6c6,55c36fb1-a3af-476e-ba17-a81f6795be8d,/items/4669293,2024-10-05 22:14:10.089116+00,Salam əleykum. \nİnşaatçılar metrosuna yaxın m...,NaN,92000.0,AZN,Məhəmməd,vasitəçi (agent),NaN,NaN,Mirzə Cabbar Məmmədzadə küç.,40.390293,49.802656,yeniləndi: 04 oktyabr 2024,190,04.10.2024,NaN,fa63b201-999d-43b5-a61a-778d9d79a6c6,NaN,Həyət evi/Bağ evi,NaN,3.0,60 m²,0.1 sot,var,var,NaN,fa63b201-999d-43b5-a61a-778d9d79a6c6,/items/4669293,İnşaatçılar m.* Yasamal r.
3,acf1aa8d-a46a-40f5-b6f2-f7a449569337,/alqi-satqi?page=250,/items/4647811,2024-10-05 22:07:37.60613+00,95000.0,AZN,Qaraçuxur q.,130 m²,"Bakı, dünən 23:55",bakı,05.10.2024,23:55,Təmirli,vipped,featured,NaN,Çıxarış var,İpoteka var,https://bina.azstatic.com/uploads/f460x345/202...,5db56980-05cc-4925-b55b-f58fb3f4d2b6,acf1aa8d-a46a-40f5-b6f2-f7a449569337,/items/4647811,2024-10-05 22:14:10.089116+00,Barter maraqlidir üstünlük maşina verilir\nHər...,NaN,95000.0,AZN,Elçin,mülkiyyətçi,NaN,NaN,Qaraçuxur qəs.,40.393614,49.981553,yeniləndi: 04 oktyabr 2024,1314,04.10.2024,NaN,5db56980-05cc-4925-b55b-f58fb3f4d2b6,NaN,Obyekt,NaN,NaN,130 m²,NaN,var,var,var,5db56980-05cc-4925-b55b-f58fb3f4d2b6,/items/4647811,Suraxanı r.* Qaraçuxur q.
4,22d840df-9283-4112-bc71-7432511fc776,/alqi-satqi?page=250,/items/4638863,2024-10-05 22:07:37.60613+00,220000.0,AZN,Əhmədli m.,"3 otaqlı, 100 m², 15/16 mərtəbə","Bakı, dünən 23:52",bakı,05.10.2024,23:52,Təmirli,NaN,NaN,Agentlik,Çıxarış var,NaN,https://bina.azstatic.com/uploads/f460x345/202...,d71cf9a9-86dd-4162-b540-6252a8659a09,22d840df-9283-4112-bc71-7432511fc776,/items/4638863,2024-10-05 22:14:10.089116+00,Əhmədli qəs. Qaçaq Nəbi küçəsi 3 otaga duzelm...,2 200 AZN/m²,220000.0,AZN,Dürdanə,vasitəçi (agent),Elite Ofis,Daşınmaz əmlak agentliyi,Qaçaq Nəbi küç.,40.390550,49.957675,yeniləndi: 04 oktyabr 2024,240,04.10.2024,NaN,d71cf9a9-86dd-4162-b540-6252a8659a09,NaN,Yeni tikili,15 / 16,3.0,100 m²,NaN,var,var,NaN,d71cf9a9-86dd-4162-b540-6252a8659a09,/items/4638863,Əhmədli m.* Xalqlar Dostluğu m.* Xətai r.* Əhm...

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100775 entries, 0 to 100774
Data columns (total 51 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id_x                 100775 non-null  str
 1   rel_url              100775 non-null  str
 2   estate_rel_url_x     100775 non-null  str
 3   datetime_scrape_x    100775 non-null  str
 4   price                100775 non-null  float64
 5   currency_x           100775 non-null  str
 6   location             100775 non-null  str
 7   attributes           100775 non-null  str
 8   city_when            100775 non-null  str
 9   city                 100775 non-null  str
 10  day_x                100775 non-null  str
 11  hour_x               100775 non-null  str
 12  repair               81612 non-null   str
 13  vip                  8596 non-null    str
 14  featured             3149 non-null    str
 15  products_label       72630 non-null   str
 16  bill_of_sale         79565 non-null   str
 17  mortgage             32939 non-null   str
 18  img_url              100775 non-null  str
 19  id_y                 100775 non-null  str
 20  estate_id            100775 non-null  str
 21  estate_rel_url_y     100775 non-null  str
 22  datetime_scrape_y    100775 non-null  str
 23  description          100510 non-null  str
 24  unit_price           75996 non-null   str
 25  total_price          100775 non-null  float64
 26  currency_y           100775 non-null  str
 27  owner_name           100118 non-null  str
 28  owner_title          100118 non-null  str
 29  shop_name            72018 non-null   str
 30  shop_title           72018 non-null   str
 31  address              100775 non-null  str
 32  lat                  100775 non-null  float64
 33  lng                  100775 non-null  float64
 34  updated              100775 non-null  str
 35  views                100775 non-null  int64
 36  day_y                100775 non-null  str
 37  hour_y               15631 non-null   str
 38  estate_details_id_x  100775 non-null  str
 39  Binanın növü         154 non-null     str
 40  Kateqoriya           100775 non-null  str
 41  Mərtəbə              75996 non-null   str
 42  Otaq sayı            91363 non-null   float64
 43  Sahə                 100775 non-null  str
 44  Torpaq sahəsi        15571 non-null   str
 45  Təmir                94774 non-null   str
 46  Çıxarış              100775 non-null  str
 47  İpoteka              32939 non-null   str
 48  estate_details_id_y  100775 non-null  str
 49  estate_rel_url       100775 non-null  str
 50  extra_info           100775 non-null  str
dtypes: float64(5), int64(1), str(45)
memory usage: 39.2 MB

In [10]:
drop = ['id_x', 'rel_url', 'estate_rel_url_x', 'datetime_scrape_x', 'city_when', 'day_x', 'hour_x', 'vip', 'featured', 'img_url', 'id_y', 'estate_id', 'estate_rel_url_y', 'datetime_scrape_y', 'owner_name', 'owner_title', 'updated', 'views', 'day_y', 'hour_y', 'estate_details_id_x', 'Binanın növü', 'estate_details_id_y', 'estate_rel_url', 'extra_info', 'Torpaq sahəsi', 'İpoteka']

In [11]:
df.drop(columns=drop, inplace=True)

In [12]:
df.head()

,price,currency_x,location,attributes,city,repair,products_label,bill_of_sale,mortgage,description,unit_price,total_price,currency_y,shop_name,shop_title,address,lat,lng,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Təmir,Çıxarış
0,499999.0,AZN,Səbail r.,"4 otaqlı, 145 m², 7/9 mərtəbə",bakı,Təmirli,NaN,Çıxarış var,NaN,"Səbail Rayonu, İzzət Nəbiyev küçəsi, Fəxri Xiy...",3 450 AZN/m²,499999.0,AZN,NaN,NaN,İzzət Nəbiyev küç.,40.358817,49.824092,Köhnə tikili,7 / 9,4.0,145 m²,var,var
1,77000.0,AZN,Biləcəri q.,"4 otaqlı, 90 m²",bakı,Təmirli,NaN,NaN,NaN,"Biləcəridə Abidəyə yaxin 91,92,202 saylı marşr...",NaN,77000.0,AZN,NaN,NaN,Biləcəri qəs.,40.420897,49.807035,Həyət evi/Bağ evi,NaN,4.0,90 m²,var,yoxdur
2,92000.0,AZN,İnşaatçılar m.,"3 otaqlı, 60 m²",bakı,Təmirli,NaN,Çıxarış var,NaN,Salam əleykum. \nİnşaatçılar metrosuna yaxın m...,NaN,92000.0,AZN,NaN,NaN,Mirzə Cabbar Məmmədzadə küç.,40.390293,49.802656,Həyət evi/Bağ evi,NaN,3.0,60 m²,var,var
3,95000.0,AZN,Qaraçuxur q.,130 m²,bakı,Təmirli,NaN,Çıxarış var,İpoteka var,Barter maraqlidir üstünlük maşina verilir\nHər...,NaN,95000.0,AZN,NaN,NaN,Qaraçuxur qəs.,40.393614,49.981553,Obyekt,NaN,NaN,130 m²,var,var
4,220000.0,AZN,Əhmədli m.,"3 otaqlı, 100 m², 15/16 mərtəbə",bakı,Təmirli,Agentlik,Çıxarış var,NaN,Əhmədli qəs. Qaçaq Nəbi küçəsi 3 otaga duzelm...,2 200 AZN/m²,220000.0,AZN,Elite Ofis,Daşınmaz əmlak agentliyi,Qaçaq Nəbi küç.,40.390550,49.957675,Yeni tikili,15 / 16,3.0,100 m²,var,var

In [13]:
df['currency_y'].unique()

<StringArray>
['AZN']
Length: 1, dtype: str

In [14]:
df.drop(columns=['currency_x', 'currency_y'], inplace=True)

In [15]:
df.head()

,price,location,attributes,city,repair,products_label,bill_of_sale,mortgage,description,unit_price,total_price,shop_name,shop_title,address,lat,lng,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Təmir,Çıxarış
0,499999.0,Səbail r.,"4 otaqlı, 145 m², 7/9 mərtəbə",bakı,Təmirli,NaN,Çıxarış var,NaN,"Səbail Rayonu, İzzət Nəbiyev küçəsi, Fəxri Xiy...",3 450 AZN/m²,499999.0,NaN,NaN,İzzət Nəbiyev küç.,40.358817,49.824092,Köhnə tikili,7 / 9,4.0,145 m²,var,var
1,77000.0,Biləcəri q.,"4 otaqlı, 90 m²",bakı,Təmirli,NaN,NaN,NaN,"Biləcəridə Abidəyə yaxin 91,92,202 saylı marşr...",NaN,77000.0,NaN,NaN,Biləcəri qəs.,40.420897,49.807035,Həyət evi/Bağ evi,NaN,4.0,90 m²,var,yoxdur
2,92000.0,İnşaatçılar m.,"3 otaqlı, 60 m²",bakı,Təmirli,NaN,Çıxarış var,NaN,Salam əleykum. \nİnşaatçılar metrosuna yaxın m...,NaN,92000.0,NaN,NaN,Mirzə Cabbar Məmmədzadə küç.,40.390293,49.802656,Həyət evi/Bağ evi,NaN,3.0,60 m²,var,var
3,95000.0,Qaraçuxur q.,130 m²,bakı,Təmirli,NaN,Çıxarış var,İpoteka var,Barter maraqlidir üstünlük maşina verilir\nHər...,NaN,95000.0,NaN,NaN,Qaraçuxur qəs.,40.393614,49.981553,Obyekt,NaN,NaN,130 m²,var,var
4,220000.0,Əhmədli m.,"3 otaqlı, 100 m², 15/16 mərtəbə",bakı,Təmirli,Agentlik,Çıxarış var,NaN,Əhmədli qəs. Qaçaq Nəbi küçəsi 3 otaga duzelm...,2 200 AZN/m²,220000.0,Elite Ofis,Daşınmaz əmlak agentliyi,Qaçaq Nəbi küç.,40.390550,49.957675,Yeni tikili,15 / 16,3.0,100 m²,var,var

In [16]:
(df['price'] == df['total_price']).sum()

np.int64(100762)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100775 entries, 0 to 100774
Data columns (total 22 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   price           100775 non-null  float64
 1   location        100775 non-null  str
 2   attributes      100775 non-null  str
 3   city            100775 non-null  str
 4   repair          81612 non-null   str
 5   products_label  72630 non-null   str
 6   bill_of_sale    79565 non-null   str
 7   mortgage        32939 non-null   str
 8   description     100510 non-null  str
 9   unit_price      75996 non-null   str
 10  total_price     100775 non-null  float64
 11  shop_name       72018 non-null   str
 12  shop_title      72018 non-null   str
 13  address         100775 non-null  str
 14  lat             100775 non-null  float64
 15  lng             100775 non-null  float64
 16  Kateqoriya      100775 non-null  str
 17  Mərtəbə         75996 non-null   str
 18  Otaq sayı       91363 non-null   float64
 19  Sahə            100775 non-null  str
 20  Təmir           94774 non-null   str
 21  Çıxarış         100775 non-null  str
dtypes: float64(5), str(17)
memory usage: 16.9 MB

In [18]:
df.drop(df[df['price'] != df['total_price']].index, inplace=True)

In [19]:
df.info()

<class 'pandas.DataFrame'>
Index: 100762 entries, 0 to 100774
Data columns (total 22 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   price           100762 non-null  float64
 1   location        100762 non-null  str
 2   attributes      100762 non-null  str
 3   city            100762 non-null  str
 4   repair          81602 non-null   str
 5   products_label  72621 non-null   str
 6   bill_of_sale    79554 non-null   str
 7   mortgage        32932 non-null   str
 8   description     100497 non-null  str
 9   unit_price      75983 non-null   str
 10  total_price     100762 non-null  float64
 11  shop_name       72009 non-null   str
 12  shop_title      72009 non-null   str
 13  address         100762 non-null  str
 14  lat             100762 non-null  float64
 15  lng             100762 non-null  float64
 16  Kateqoriya      100762 non-null  str
 17  Mərtəbə         75983 non-null   str
 18  Otaq sayı       91350 non-null   float64
 19  Sahə            100762 non-null  str
 20  Təmir           94762 non-null   str
 21  Çıxarış         100762 non-null  str
dtypes: float64(5), str(17)
memory usage: 17.7 MB

In [20]:
df.drop(columns=['total_price'], inplace=True)

In [21]:
df.head()

,price,location,attributes,city,repair,products_label,bill_of_sale,mortgage,description,unit_price,shop_name,shop_title,address,lat,lng,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Təmir,Çıxarış
0,499999.0,Səbail r.,"4 otaqlı, 145 m², 7/9 mərtəbə",bakı,Təmirli,NaN,Çıxarış var,NaN,"Səbail Rayonu, İzzət Nəbiyev küçəsi, Fəxri Xiy...",3 450 AZN/m²,NaN,NaN,İzzət Nəbiyev küç.,40.358817,49.824092,Köhnə tikili,7 / 9,4.0,145 m²,var,var
1,77000.0,Biləcəri q.,"4 otaqlı, 90 m²",bakı,Təmirli,NaN,NaN,NaN,"Biləcəridə Abidəyə yaxin 91,92,202 saylı marşr...",NaN,NaN,NaN,Biləcəri qəs.,40.420897,49.807035,Həyət evi/Bağ evi,NaN,4.0,90 m²,var,yoxdur
2,92000.0,İnşaatçılar m.,"3 otaqlı, 60 m²",bakı,Təmirli,NaN,Çıxarış var,NaN,Salam əleykum. \nİnşaatçılar metrosuna yaxın m...,NaN,NaN,NaN,Mirzə Cabbar Məmmədzadə küç.,40.390293,49.802656,Həyət evi/Bağ evi,NaN,3.0,60 m²,var,var
3,95000.0,Qaraçuxur q.,130 m²,bakı,Təmirli,NaN,Çıxarış var,İpoteka var,Barter maraqlidir üstünlük maşina verilir\nHər...,NaN,NaN,NaN,Qaraçuxur qəs.,40.393614,49.981553,Obyekt,NaN,NaN,130 m²,var,var
4,220000.0,Əhmədli m.,"3 otaqlı, 100 m², 15/16 mərtəbə",bakı,Təmirli,Agentlik,Çıxarış var,NaN,Əhmədli qəs. Qaçaq Nəbi küçəsi 3 otaga duzelm...,2 200 AZN/m²,Elite Ofis,Daşınmaz əmlak agentliyi,Qaçaq Nəbi küç.,40.390550,49.957675,Yeni tikili,15 / 16,3.0,100 m²,var,var

In [22]:
df.drop(columns = ['attributes', 'description'], inplace=True)

In [23]:
df.head()

,price,location,city,repair,products_label,bill_of_sale,mortgage,unit_price,shop_name,shop_title,address,lat,lng,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Təmir,Çıxarış
0,499999.0,Səbail r.,bakı,Təmirli,NaN,Çıxarış var,NaN,3 450 AZN/m²,NaN,NaN,İzzət Nəbiyev küç.,40.358817,49.824092,Köhnə tikili,7 / 9,4.0,145 m²,var,var
1,77000.0,Biləcəri q.,bakı,Təmirli,NaN,NaN,NaN,NaN,NaN,NaN,Biləcəri qəs.,40.420897,49.807035,Həyət evi/Bağ evi,NaN,4.0,90 m²,var,yoxdur
2,92000.0,İnşaatçılar m.,bakı,Təmirli,NaN,Çıxarış var,NaN,NaN,NaN,NaN,Mirzə Cabbar Məmmədzadə küç.,40.390293,49.802656,Həyət evi/Bağ evi,NaN,3.0,60 m²,var,var
3,95000.0,Qaraçuxur q.,bakı,Təmirli,NaN,Çıxarış var,İpoteka var,NaN,NaN,NaN,Qaraçuxur qəs.,40.393614,49.981553,Obyekt,NaN,NaN,130 m²,var,var
4,220000.0,Əhmədli m.,bakı,Təmirli,Agentlik,Çıxarış var,NaN,2 200 AZN/m²,Elite Ofis,Daşınmaz əmlak agentliyi,Qaçaq Nəbi küç.,40.390550,49.957675,Yeni tikili,15 / 16,3.0,100 m²,var,var

In [24]:
df.info()

<class 'pandas.DataFrame'>
Index: 100762 entries, 0 to 100774
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   price           100762 non-null  float64
 1   location        100762 non-null  str
 2   city            100762 non-null  str
 3   repair          81602 non-null   str
 4   products_label  72621 non-null   str
 5   bill_of_sale    79554 non-null   str
 6   mortgage        32932 non-null   str
 7   unit_price      75983 non-null   str
 8   shop_name       72009 non-null   str
 9   shop_title      72009 non-null   str
 10  address         100762 non-null  str
 11  lat             100762 non-null  float64
 12  lng             100762 non-null  float64
 13  Kateqoriya      100762 non-null  str
 14  Mərtəbə         75983 non-null   str
 15  Otaq sayı       91350 non-null   float64
 16  Sahə            100762 non-null  str
 17  Təmir           94762 non-null   str
 18  Çıxarış         100762 non-null  str
dtypes: float64(4), str(15)
memory usage: 15.4 MB

In [25]:
df.nunique()

price              2772
location            142
city                  8
repair                1
products_label        2
bill_of_sale          1
mortgage              1
unit_price          814
shop_name           316
shop_title            1
address           16716
lat               57988
lng               57204
Kateqoriya            7
Mərtəbə             392
Otaq sayı            19
Sahə               1804
Təmir                 2
Çıxarış               2
dtype: int64

In [26]:
df['products_label'].unique()

<StringArray>
[nan, 'Agentlik', 'Kompleks']
Length: 3, dtype: str

In [27]:
dropp=['repair', 'bill_of_sale', 'mortgage', 'address']
df.drop(columns=dropp, inplace=True)

In [28]:
df.head()

,price,location,city,products_label,unit_price,shop_name,shop_title,lat,lng,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Təmir,Çıxarış
0,499999.0,Səbail r.,bakı,NaN,3 450 AZN/m²,NaN,NaN,40.358817,49.824092,Köhnə tikili,7 / 9,4.0,145 m²,var,var
1,77000.0,Biləcəri q.,bakı,NaN,NaN,NaN,NaN,40.420897,49.807035,Həyət evi/Bağ evi,NaN,4.0,90 m²,var,yoxdur
2,92000.0,İnşaatçılar m.,bakı,NaN,NaN,NaN,NaN,40.390293,49.802656,Həyət evi/Bağ evi,NaN,3.0,60 m²,var,var
3,95000.0,Qaraçuxur q.,bakı,NaN,NaN,NaN,NaN,40.393614,49.981553,Obyekt,NaN,NaN,130 m²,var,var
4,220000.0,Əhmədli m.,bakı,Agentlik,2 200 AZN/m²,Elite Ofis,Daşınmaz əmlak agentliyi,40.390550,49.957675,Yeni tikili,15 / 16,3.0,100 m²,var,var

In [29]:
df.info()

<class 'pandas.DataFrame'>
Index: 100762 entries, 0 to 100774
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   price           100762 non-null  float64
 1   location        100762 non-null  str
 2   city            100762 non-null  str
 3   products_label  72621 non-null   str
 4   unit_price      75983 non-null   str
 5   shop_name       72009 non-null   str
 6   shop_title      72009 non-null   str
 7   lat             100762 non-null  float64
 8   lng             100762 non-null  float64
 9   Kateqoriya      100762 non-null  str
 10  Mərtəbə         75983 non-null   str
 11  Otaq sayı       91350 non-null   float64
 12  Sahə            100762 non-null  str
 13  Təmir           94762 non-null   str
 14  Çıxarış         100762 non-null  str
dtypes: float64(4), str(11)
memory usage: 12.3 MB

In [30]:
df['products_label'].unique()

<StringArray>
[nan, 'Agentlik', 'Kompleks']
Length: 3, dtype: str

In [31]:
df['products_label'].value_counts()

products_label
Agentlik    71972
Kompleks      649
Name: count, dtype: int64

In [32]:
df.groupby('products_label')['price'].mean()

products_label
Agentlik    351606.500750
Kompleks    564681.952234
Name: price, dtype: float64

In [33]:
df['products_label'] = df['products_label'].fillna(df['products_label'].mode()[0])

In [34]:
df.info()

<class 'pandas.DataFrame'>
Index: 100762 entries, 0 to 100774
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   price           100762 non-null  float64
 1   location        100762 non-null  str
 2   city            100762 non-null  str
 3   products_label  100762 non-null  str
 4   unit_price      75983 non-null   str
 5   shop_name       72009 non-null   str
 6   shop_title      72009 non-null   str
 7   lat             100762 non-null  float64
 8   lng             100762 non-null  float64
 9   Kateqoriya      100762 non-null  str
 10  Mərtəbə         75983 non-null   str
 11  Otaq sayı       91350 non-null   float64
 12  Sahə            100762 non-null  str
 13  Təmir           94762 non-null   str
 14  Çıxarış         100762 non-null  str
dtypes: float64(4), str(11)
memory usage: 12.3 MB

In [35]:
df['unit_price'].unique()

<StringArray>
['3 450 AZN/m²',            nan, '2 200 AZN/m²', '5 000 AZN/m²',
 '3 700 AZN/m²', '1 820 AZN/m²', '2 520 AZN/m²', '1 800 AZN/m²',
 '2 060 AZN/m²', '3 480 AZN/m²',
 ...
   '552 AZN/m²',   '667 AZN/m²',   '901 AZN/m²',   '921 AZN/m²',
   '946 AZN/m²',   '702 AZN/m²',   '811 AZN/m²',   '948 AZN/m²',
   '955 AZN/m²', '5 720 AZN/m²']
Length: 815, dtype: str

In [36]:
df['unit_price'] = df['unit_price'].str.replace(' ', '').str.extract('(\d+)')[0]

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
/var/folders/hy/n420tyvd6m54vsvk843qjrbc0000gn/T/ipykernel_27449/3157226976.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df['unit_price'] = df['unit_price'].str.replace(' ', '').str.extract('(\d+)')[0]

In [37]:
df.head()

,price,location,city,products_label,unit_price,shop_name,shop_title,lat,lng,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Təmir,Çıxarış
0,499999.0,Səbail r.,bakı,Agentlik,3450,NaN,NaN,40.358817,49.824092,Köhnə tikili,7 / 9,4.0,145 m²,var,var
1,77000.0,Biləcəri q.,bakı,Agentlik,NaN,NaN,NaN,40.420897,49.807035,Həyət evi/Bağ evi,NaN,4.0,90 m²,var,yoxdur
2,92000.0,İnşaatçılar m.,bakı,Agentlik,NaN,NaN,NaN,40.390293,49.802656,Həyət evi/Bağ evi,NaN,3.0,60 m²,var,var
3,95000.0,Qaraçuxur q.,bakı,Agentlik,NaN,NaN,NaN,40.393614,49.981553,Obyekt,NaN,NaN,130 m²,var,var
4,220000.0,Əhmədli m.,bakı,Agentlik,2200,Elite Ofis,Daşınmaz əmlak agentliyi,40.390550,49.957675,Yeni tikili,15 / 16,3.0,100 m²,var,var

In [38]:
df.info()

<class 'pandas.DataFrame'>
Index: 100762 entries, 0 to 100774
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   price           100762 non-null  float64
 1   location        100762 non-null  str
 2   city            100762 non-null  str
 3   products_label  100762 non-null  str
 4   unit_price      75983 non-null   str
 5   shop_name       72009 non-null   str
 6   shop_title      72009 non-null   str
 7   lat             100762 non-null  float64
 8   lng             100762 non-null  float64
 9   Kateqoriya      100762 non-null  str
 10  Mərtəbə         75983 non-null   str
 11  Otaq sayı       91350 non-null   float64
 12  Sahə            100762 non-null  str
 13  Təmir           94762 non-null   str
 14  Çıxarış         100762 non-null  str
dtypes: float64(4), str(11)
memory usage: 12.3 MB

In [39]:
df['unit_price'] = pd.to_numeric(df['unit_price'], errors='coerce')

In [40]:
df['Sahə'] = df['Sahə'].str.extract('(\d+)')[0].astype(float)

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
/var/folders/hy/n420tyvd6m54vsvk843qjrbc0000gn/T/ipykernel_27449/3920885092.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df['Sahə'] = df['Sahə'].str.extract('(\d+)')[0].astype(float)

In [41]:
mask = df['unit_price'].isna()
df.loc[mask, 'unit_price'] = df.loc[mask, 'price'] / df.loc[mask, 'Sahə']

In [42]:
df.info()

<class 'pandas.DataFrame'>
Index: 100762 entries, 0 to 100774
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   price           100762 non-null  float64
 1   location        100762 non-null  str
 2   city            100762 non-null  str
 3   products_label  100762 non-null  str
 4   unit_price      100762 non-null  float64
 5   shop_name       72009 non-null   str
 6   shop_title      72009 non-null   str
 7   lat             100762 non-null  float64
 8   lng             100762 non-null  float64
 9   Kateqoriya      100762 non-null  str
 10  Mərtəbə         75983 non-null   str
 11  Otaq sayı       91350 non-null   float64
 12  Sahə            100762 non-null  float64
 13  Təmir           94762 non-null   str
 14  Çıxarış         100762 non-null  str
dtypes: float64(6), str(9)
memory usage: 12.3 MB

In [43]:
df.head()

,price,location,city,products_label,unit_price,shop_name,shop_title,lat,lng,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Təmir,Çıxarış
0,499999.0,Səbail r.,bakı,Agentlik,3450.000000,NaN,NaN,40.358817,49.824092,Köhnə tikili,7 / 9,4.0,145.0,var,var
1,77000.0,Biləcəri q.,bakı,Agentlik,855.555556,NaN,NaN,40.420897,49.807035,Həyət evi/Bağ evi,NaN,4.0,90.0,var,yoxdur
2,92000.0,İnşaatçılar m.,bakı,Agentlik,1533.333333,NaN,NaN,40.390293,49.802656,Həyət evi/Bağ evi,NaN,3.0,60.0,var,var
3,95000.0,Qaraçuxur q.,bakı,Agentlik,730.769231,NaN,NaN,40.393614,49.981553,Obyekt,NaN,NaN,130.0,var,var
4,220000.0,Əhmədli m.,bakı,Agentlik,2200.000000,Elite Ofis,Daşınmaz əmlak agentliyi,40.390550,49.957675,Yeni tikili,15 / 16,3.0,100.0,var,var

In [44]:
df['shop_title'].unique()

<StringArray>
[nan, 'Daşınmaz əmlak agentliyi']
Length: 2, dtype: str

In [45]:
df.nunique()

price              2772
location            142
city                  8
products_label        2
unit_price         5245
shop_name           316
shop_title            1
lat               57988
lng               57204
Kateqoriya            7
Mərtəbə             392
Otaq sayı            19
Sahə                663
Təmir                 2
Çıxarış               2
dtype: int64

In [46]:
df.drop(columns=['shop_title'], inplace=True)

In [47]:
df.info()

<class 'pandas.DataFrame'>
Index: 100762 entries, 0 to 100774
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   price           100762 non-null  float64
 1   location        100762 non-null  str
 2   city            100762 non-null  str
 3   products_label  100762 non-null  str
 4   unit_price      100762 non-null  float64
 5   shop_name       72009 non-null   str
 6   lat             100762 non-null  float64
 7   lng             100762 non-null  float64
 8   Kateqoriya      100762 non-null  str
 9   Mərtəbə         75983 non-null   str
 10  Otaq sayı       91350 non-null   float64
 11  Sahə            100762 non-null  float64
 12  Təmir           94762 non-null   str
 13  Çıxarış         100762 non-null  str
dtypes: float64(6), str(8)
memory usage: 11.5 MB

In [48]:
df['shop_name'].nunique()

316

In [49]:
df['shop_name'] = df['shop_name'].fillna('Unknown')

In [50]:
df.info()

<class 'pandas.DataFrame'>
Index: 100762 entries, 0 to 100774
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   price           100762 non-null  float64
 1   location        100762 non-null  str
 2   city            100762 non-null  str
 3   products_label  100762 non-null  str
 4   unit_price      100762 non-null  float64
 5   shop_name       100762 non-null  str
 6   lat             100762 non-null  float64
 7   lng             100762 non-null  float64
 8   Kateqoriya      100762 non-null  str
 9   Mərtəbə         75983 non-null   str
 10  Otaq sayı       91350 non-null   float64
 11  Sahə            100762 non-null  float64
 12  Təmir           94762 non-null   str
 13  Çıxarış         100762 non-null  str
dtypes: float64(6), str(8)
memory usage: 11.5 MB

In [51]:
df['Mərtəbə']

0           7 / 9
1             NaN
2             NaN
3             NaN
4         15 / 16
           ...
100770        NaN
100771        NaN
100772        NaN
100773     4 / 19
100774    13 / 15
Name: Mərtəbə, Length: 100762, dtype: str

In [52]:
df['Mərtəbə'] = df['Mərtəbə'].str.extract('(\d+)')[0]

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
/var/folders/hy/n420tyvd6m54vsvk843qjrbc0000gn/T/ipykernel_27449/3013731193.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df['Mərtəbə'] = df['Mərtəbə'].str.extract('(\d+)')[0]

In [53]:
df['Mərtəbə'] = df['Mərtəbə'].astype(float)

In [54]:
median_value = df[df['Kateqoriya'].isin(['Köhnə tikili', 'Yeni tikili'])]['Mərtəbə'].median()

def fill_floor(row):
    if pd.isna(row['Mərtəbə']):
        if row['Kateqoriya'] in ['Köhnə tikili', 'Yeni tikili']:
            return median_value
        else:
            return 0
    return row['Mərtəbə']

df['Mərtəbə'] = df.apply(fill_floor, axis=1)

df.head()

,price,location,city,products_label,unit_price,shop_name,lat,lng,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Təmir,Çıxarış
0,499999.0,Səbail r.,bakı,Agentlik,3450.000000,Unknown,40.358817,49.824092,Köhnə tikili,7.0,4.0,145.0,var,var
1,77000.0,Biləcəri q.,bakı,Agentlik,855.555556,Unknown,40.420897,49.807035,Həyət evi/Bağ evi,0.0,4.0,90.0,var,yoxdur
2,92000.0,İnşaatçılar m.,bakı,Agentlik,1533.333333,Unknown,40.390293,49.802656,Həyət evi/Bağ evi,0.0,3.0,60.0,var,var
3,95000.0,Qaraçuxur q.,bakı,Agentlik,730.769231,Unknown,40.393614,49.981553,Obyekt,0.0,NaN,130.0,var,var
4,220000.0,Əhmədli m.,bakı,Agentlik,2200.000000,Elite Ofis,40.390550,49.957675,Yeni tikili,15.0,3.0,100.0,var,var

In [55]:
df['Kateqoriya'].unique()

<StringArray>
[     'Köhnə tikili', 'Həyət evi/Bağ evi',            'Obyekt',
       'Yeni tikili',            'Torpaq',              'Ofis',
             'Qaraj']
Length: 7, dtype: str

In [56]:
df.info()

<class 'pandas.DataFrame'>
Index: 100762 entries, 0 to 100774
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   price           100762 non-null  float64
 1   location        100762 non-null  str
 2   city            100762 non-null  str
 3   products_label  100762 non-null  str
 4   unit_price      100762 non-null  float64
 5   shop_name       100762 non-null  str
 6   lat             100762 non-null  float64
 7   lng             100762 non-null  float64
 8   Kateqoriya      100762 non-null  str
 9   Mərtəbə         100762 non-null  float64
 10  Otaq sayı       91350 non-null   float64
 11  Sahə            100762 non-null  float64
 12  Təmir           94762 non-null   str
 13  Çıxarış         100762 non-null  str
dtypes: float64(7), str(7)
memory usage: 11.5 MB

In [57]:
df.head(20)

,price,location,city,products_label,unit_price,shop_name,lat,lng,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Təmir,Çıxarış
0,499999.0,Səbail r.,bakı,Agentlik,3450.000000,Unknown,40.358817,49.824092,Köhnə tikili,7.0,4.0,145.0,var,var
1,77000.0,Biləcəri q.,bakı,Agentlik,855.555556,Unknown,40.420897,49.807035,Həyət evi/Bağ evi,0.0,4.0,90.0,var,yoxdur
2,92000.0,İnşaatçılar m.,bakı,Agentlik,1533.333333,Unknown,40.390293,49.802656,Həyət evi/Bağ evi,0.0,3.0,60.0,var,var
3,95000.0,Qaraçuxur q.,bakı,Agentlik,730.769231,Unknown,40.393614,49.981553,Obyekt,0.0,NaN,130.0,var,var
4,220000.0,Əhmədli m.,bakı,Agentlik,2200.000000,Elite Ofis,40.390550,49.957675,Yeni tikili,15.0,3.0,100.0,var,var
5,650000.0,Sahil m.,bakı,Agentlik,5000.000000,Unknown,40.372458,49.838651,Köhnə tikili,3.0,4.0,130.0,var,var
6,259000.0,Sahil m.,bakı,Agentlik,3700.000000,Unknown,40.374144,49.849868,Köhnə tikili,2.0,3.0,70.0,var,var
7,279000.0,Bayıl q.,bakı,Agentlik,1820.000000,Unknown,40.349737,49.831389,Yeni tikili,3.0,3.0,153.0,yoxdur,var
8,3000000.0,Nizami m.,bakı,Agentlik,6185.567010,Unknown,40.383231,49.826150,Obyekt,0.0,NaN,485.0,var,var
9,262000.0,Memar Əcəmi m.,bakı,Agentlik,2520.000000,MS Group,40.407959,49.816227,Yeni tikili,11.0,3.0,104.0,var,yoxdur
10,1050000.0,Masazır q.,bakı,Agentlik,2916.666667,Unknown,40.481764,49.755836,Obyekt,0.0,NaN,360.0,NaN,yoxdur
11,275000.0,Qara Qarayev m.,bakı,Agentlik,6111.111111,Unknown,40.417903,49.933907,Obyekt,0.0,NaN,45.0,var,var
12,153000.0,İnşaatçılar m.,bakı,Agentlik,1800.000000,New House Nəsimi,40.393529,49.795103,Yeni tikili,19.0,4.0,85.0,var,var
13,450000.0,Novxanı q.,bakı,Agentlik,478.723404,Unknown,40.525441,49.757032,Həyət evi/Bağ evi,0.0,9.0,940.0,yoxdur,var
14,330000.0,Nəriman Nərimanov m.,bakı,Agentlik,2060.000000,VİP House Elmlər,40.400400,49.867113,Yeni tikili,3.0,3.0,160.0,var,var
15,195000.0,8 Noyabr m.,bakı,Agentlik,3480.000000,VİP House Elmlər,40.400613,49.830908,Yeni tikili,10.0,2.0,56.0,var,var
16,150000.0,Neftçilər m.,bakı,Agentlik,2140.000000,Unknown,40.410225,49.943306,Köhnə tikili,4.0,3.0,70.0,var,var
17,77000.0,Masazır q.,bakı,Agentlik,1070.000000,Unknown,40.491266,49.755474,Yeni tikili,5.0,3.0,72.0,var,yoxdur
18,260000.0,28 May m.,bakı,Agentlik,3714.285714,Unknown,40.386797,49.855109,Obyekt,0.0,NaN,70.0,yoxdur,var
19,455000.0,Əhmədli m.,bakı,Agentlik,2020.000000,Unknown,40.385212,49.956013,Yeni tikili,12.0,5.0,225.0,var,var

In [58]:
df['Otaq sayı'] = df['Otaq sayı'].fillna(0)

In [59]:
df.head()

,price,location,city,products_label,unit_price,shop_name,lat,lng,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Təmir,Çıxarış
0,499999.0,Səbail r.,bakı,Agentlik,3450.000000,Unknown,40.358817,49.824092,Köhnə tikili,7.0,4.0,145.0,var,var
1,77000.0,Biləcəri q.,bakı,Agentlik,855.555556,Unknown,40.420897,49.807035,Həyət evi/Bağ evi,0.0,4.0,90.0,var,yoxdur
2,92000.0,İnşaatçılar m.,bakı,Agentlik,1533.333333,Unknown,40.390293,49.802656,Həyət evi/Bağ evi,0.0,3.0,60.0,var,var
3,95000.0,Qaraçuxur q.,bakı,Agentlik,730.769231,Unknown,40.393614,49.981553,Obyekt,0.0,0.0,130.0,var,var
4,220000.0,Əhmədli m.,bakı,Agentlik,2200.000000,Elite Ofis,40.390550,49.957675,Yeni tikili,15.0,3.0,100.0,var,var

In [60]:
df['Təmir'] = df['Təmir'].fillna(df['Təmir'].mode()[0])

In [61]:
df.info()

<class 'pandas.DataFrame'>
Index: 100762 entries, 0 to 100774
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   price           100762 non-null  float64
 1   location        100762 non-null  str
 2   city            100762 non-null  str
 3   products_label  100762 non-null  str
 4   unit_price      100762 non-null  float64
 5   shop_name       100762 non-null  str
 6   lat             100762 non-null  float64
 7   lng             100762 non-null  float64
 8   Kateqoriya      100762 non-null  str
 9   Mərtəbə         100762 non-null  float64
 10  Otaq sayı       100762 non-null  float64
 11  Sahə            100762 non-null  float64
 12  Təmir           100762 non-null  str
 13  Çıxarış         100762 non-null  str
dtypes: float64(7), str(7)
memory usage: 11.5 MB

In [62]:
df.head()

,price,location,city,products_label,unit_price,shop_name,lat,lng,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Təmir,Çıxarış
0,499999.0,Səbail r.,bakı,Agentlik,3450.000000,Unknown,40.358817,49.824092,Köhnə tikili,7.0,4.0,145.0,var,var
1,77000.0,Biləcəri q.,bakı,Agentlik,855.555556,Unknown,40.420897,49.807035,Həyət evi/Bağ evi,0.0,4.0,90.0,var,yoxdur
2,92000.0,İnşaatçılar m.,bakı,Agentlik,1533.333333,Unknown,40.390293,49.802656,Həyət evi/Bağ evi,0.0,3.0,60.0,var,var
3,95000.0,Qaraçuxur q.,bakı,Agentlik,730.769231,Unknown,40.393614,49.981553,Obyekt,0.0,0.0,130.0,var,var
4,220000.0,Əhmədli m.,bakı,Agentlik,2200.000000,Elite Ofis,40.390550,49.957675,Yeni tikili,15.0,3.0,100.0,var,var

In [63]:
df.to_csv('cleaned_house_sale.csv', index=False)